# Streamlit Cloud Secrets Configuration
# Copy this entire file content to Streamlit Cloud

# ========================================
# AWS CREDENTIALS
# ========================================
# Get these from AWS Console → IAM → Security Credentials
AWS_ACCESS_KEY_ID = "YOUR_AWS_ACCESS_KEY_HERE"
AWS_SECRET_ACCESS_KEY = "YOUR_AWS_SECRET_KEY_HERE"
AWS_DEFAULT_REGION = "eu-north-1"

# ========================================
# S3 CONFIGURATION
# ========================================
S3_BUCKET_NAME = "image-caption-bucket-karthik"

# ========================================
# DYNAMODB CONFIGURATION
# ========================================
DYNAMODB_TABLE_NAME = "image_captions"

# ========================================
# HUGGING FACE API (Optional)
# ========================================
# Current token (keep or replace with your own)
hf_api_token = "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"

# ========================================
# INSTRUCTIONS FOR STREAMLIT CLOUD:
# ========================================
# 1. Go to: https://share.streamlit.io/
# 2. Connect your GitHub repository
# 3. Click "Advanced settings" → "Secrets"
# 4. Copy EVERYTHING from line 4 to line 24 above
# 5. Paste into the secrets text box
# 6. Click "Save"
# 7. Deploy!
#
# IMPORTANT: Replace YOUR_AWS_ACCESS_KEY_HERE and 
# YOUR_AWS_SECRET_KEY_HERE with your actual AWS credentials
